<?php

namespace App\ECommerceBundle\Controller\SAV;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TicketController__JMSInjector
{
    public static function inject($container) {
        $instance = new \App\ECommerceBundle\Controller\SAV\TicketController();
        return $instance;
    }
}
