<?php

namespace App\ECommerceBundle\Controller\Product;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PriceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \App\ECommerceBundle\Controller\Product\PriceController();
        return $instance;
    }
}
