<?php

namespace App\MediaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CropingController__JMSInjector
{
    public static function inject($container) {
        $instance = new \App\MediaBundle\Controller\CropingController();
        return $instance;
    }
}
