<?php

namespace App\ECommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogRepository extends EntityRepository
{
    
    /*
     *  Recupere le nombre de Catalogue
     *  
     *  @return $total : Nombre de catalogue
    */
   public function getTotal($oRequest) {
       
        //$qb_count = clone $qb;
       
       $qb_count = $this->createQueryBuilder('a');
       $qb_count->select('COUNT(a)');
       $total =  $qb_count->getQuery()->getSingleScalarResult();
        
        return $total;
   }
   
   
   /*
    * Recupere le nombre de catalogue // TODO confimer avec ADLM
    * 
    * @return  $result : catalogue filtré en fonction des paramètres saisies
   */
   public function getResult($oRequest, $container) {
       
            $qb = $this->createQueryBuilder('a');
            $qb->select('a');
            
            $filters = $oRequest->get('filters');
            $lang = $oRequest->get('lang');
            if(empty($lang)){
                $lang = $container->getParameter('locale');
            }
            $qb->setFirstResult($oRequest->get('iDisplayStart'));
            $qb->setMaxResults($oRequest->get('iDisplayLength'));
            $result =  $qb->getQuery()->getResult();
            
            return $result;
   }
}
