services:
    app.media.twig:
        class: App\MediaBundle\Twig\MediaExtension
        arguments:           
          - "@service_container"
        tags:
            - { name: twig.extension }

    app.media.services.media:
            class: App\MediaBundle\Services\MediaService
            arguments:
              - "@service_container"
