<?php

namespace App\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FileManagerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \App\AdminBundle\Controller\FileManagerController();
        return $instance;
    }
}
