<?php

namespace App\ECommerceBundle\Controller\Product;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProductController__JMSInjector
{
    public static function inject($container) {
        require_once '/Users/adeloustad/Sites/Total-Bitume/app/cache/dev/jms_diextra/proxies/App-ECommerceBundle-Controller-Product-ProductController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('App\\ECommerceBundle\\Controller\\Product\\ProductController' => array('indexAction' => array(0 => 'security.access.method_interceptor'), 'createAction' => array(0 => 'security.access.method_interceptor'), 'newAction' => array(0 => 'security.access.method_interceptor'), 'editAction' => array(0 => 'security.access.method_interceptor'), 'updateAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy7bf30588_e9ba15be1ed50f9df92b9921f3d0156f3a528ff9\__CG__\App\ECommerceBundle\Controller\Product\ProductController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
