<?php

namespace App\ECommerceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CommandController__JMSInjector
{
    public static function inject($container) {
        $instance = new \App\ECommerceBundle\Controller\CommandController();
        return $instance;
    }
}
