services:
    app.ecommercebundle.sav.ticket:
        class: App\ECommerceBundle\Form\Type\SAV\TicketType
        arguments: [@service_container]
        tags:
           - { name: form.type, alias: app_ecommercebundle_sav_ticket }
